import '~/styles/main.css';

import type { PropsWithChildren } from 'react';

import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

interface RootLayoutProps extends PropsWithChildren {}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1, minimum-scale=1',
};

const font = Inter({ subsets: ['latin'] });

export default function RootLayout(props: RootLayoutProps) {
  let { children } = props;

  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
